config/routes.rb
Rails.application.routes.draw do

  get '/landing', to: "pages#landing"

  get 'pages/menu'
  get 'bets/home'
  get 'savings/index'
  get '/graphs/home'
  post 'deposits', to: "users#deposit"
  post 'withdrawals', to: "users#withdraw"

  # get '/statistic', to: "pages#home"
  get 'horrible_facts/random', to: "horrible_facts#random", as: :random
  resources :consumptions, only: [:create, :update]
  resources :horrible_facts, only: [:index, :show,]
  resources :savings, only: [:index]
  resources :bets, only: [:index, :show, :new, :create]
  devise_for :users



  root to: 'consumptions#home'

  get "/style", to: "pages#style"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/bet.rb
class Bet < ApplicationRecord
  belongs_to :user
  validates :amount, numericality: { greater_than_or_equal_to: 1 }
end

app/controllers/bets_controller.rb
class BetsController < ApplicationController

  def home
    @navbar_title = "Challenge"
    @user = current_user
    @pendingbets = []

    @user.bets.each do |b|
      @pendingbets << b if b.status == "pending"
    end
  end


  def index
    @navbar_title = "Challenge"
    @user = current_user
    @pendingbets = []

    @user.bets.each do |b|
      @pendingbets << b if b.status == "pending"
    end
  end

  # def show
  #   @user = current_user
  #   @bet = Bet.find(params[:id])
  # end

  def show
    @navbar_title = "Challenge"
    @user = current_user
    # get all the User's consumptions
    @bet = Bet.find(params[:id])
    startdate = @bet.date
    enddate = @bet.date + 6

    arr1 = []
    @user.consumptions.each do |c|
      arr1 << c.daily_actual_consumption if c.date >= startdate && c.date <= enddate
    end
    @consumption = arr1.sum
    if @consumption <= @bet.goal # bet is won
       p @user.wallet
       @user.wallet += @bet.amount
       @user.save!
       p @user.wallet
       @betmessage = "Congrats!"
       @bet.status = "Congrats! you did it! We are now sending back #{@bet.amount} CAD to your balance"
       @bet.save!
    else # bet is lost
      @betmessage = "You failed!"
       @bet.status = "You failed! We are now sending on your behalf #{@bet.amount} CAD to an Action on Smoking and Health Association"
       @bet.save!
    end
  end



  def new
    @navbar_title = "Challenge"
    @user = current_user
    @bet = Bet.new

    startdate = Date.today - 7
    enddate = Date.today - 1

    arr1 = []
    @user.consumptions.each do |c|
      arr1 << c.daily_actual_consumption if c.date >= startdate && c.date <= enddate
    end
    @consumption = arr1.sum

  end


  def create
    @navbar_title = "Challenge"
    @user = current_user
    # raise
    @bet = Bet.new(bet_params)
    if @bet.amount <= @user.wallet
      @bet.date = Date.today + 1
      # write code to update wallet
      @user.wallet -= @bet.amount
      @user.save!
      # write code to update new bet
      @bet.user = current_user
      @bet.status = 'pending'
      # @bet.date = Date.today
      @bet.save!
      redirect_to bets_home_path
      # flash[:alert] = 'Challenge submitted !'
      # format.html { redirect_to bets_home_path, alert: 'Challenge submitted !' }
    else
      # code to show some error
      redirect_to new_bet_path
      # flash[:alert] = 'Not enough money on your balance'
      # format.html { redirect_to new_bet_path, alert: 'Not enough money on your balance' }
    end
  end




private

def bet_params
  params.require(:bet).permit(:amount, :goal)
end


end

app/views/bets/home.html.erb
<div class="lo--main-container">
<!-- <h1>Bets#home</h1> -->
<!-- <p>Find me in app/views/bets/home.html.erb</p> -->

<div  class="text-bet-home" >
You have <%= @pendingbets.length %> challenge<%= @pendingbets.size == 0 ? "" : "s" %>
</div>

<div class="text-link">
  <div class="text-link-bet-home" >
    <%= link_to bets_path do %>
      <span>Check results <i class="far fa-check-square"></i></span>
    <% end %>
  </div>

  <div class="text-link-bet-home" >
    <%= link_to "New challenge", new_bet_path %> <i class="fas fa-dumbbell"></i>
  </div>
</div>



<div class="bet-home-field-tag-lo--circle">
  <input type="number" id="wallet-money" placeholder="0" >
</div>


<div class="text2-bet-home" >
Your balance is  <%= @user.wallet %> CAD
</div>

<div class="2-btns" style="
    display: flex;
    justify-content: space-around;">
  <%= form_tag(deposits_path, method: :post) do  %>
  <%= hidden_field_tag "user[wallet_deposit]" %>
  <div class="bet-home-submit-btn">
    <%= submit_tag("Deposit") %> <!-- placeholder ?  -->
  </div>
  <% end %>

  <%= form_tag(withdrawals_path, method: :post) do  %>
  <%= hidden_field_tag("user[wallet_withdraw]", 0) %>
  <div class="bet-home-submit-btn">
    <%= submit_tag("Withdraw") %>
  </div>
  <% end %>
</div>

<%= javascript_pack_tag "new-wallet" %>

app/views/bets/index.html.erb
<div class="lo--main-container">

<!-- <p>Find me in app/views/bets.index.html.erb</p> -->
    <% if @pendingbets.length == 0 %>

      <p>You have no pending challenges</p>

    <% else %>

      <h5>Your pending challenges:</h5>

    <div>
      <% @pendingbets.each do |b| %>
        <% if Date.today > b.date + 7 %>
          <div class="text-bet-index">
            <div class="lo-bet-title">Bet # <%= b.id %></div>
            <div class="lo-bet-description">

              <div class="lo-bet-amount">
                <p class="title">Amount</p>
                <p class="content"><%= b.amount %> CAD</p>
              </div>

              <div class="lo-bet-goal">
                <p class="title">Goal</p>
                <p class="content"><%= b.goal %> cigarettes</p>
              </div>

            </div>
          </div>

          <div class="text-link-bet-home">
            <%= link_to "Check the result", bet_path(:id => b.id) %>
          </div>

        <% else %>
          <div class="text-bet-index">
            <div class="lo-bet-title">Bet # <%= b.id %></div>
            <div class="lo-bet-description">

              <div class="lo-bet-amount">
                <p class="title">Amount</p>
                <p class="content"><%= b.amount %> CAD</p>
              </div>

              <div class="lo-bet-goal">
                <p class="title">Goal</p>
                <p class="content"><%= b.goal %> cigarettes</p>
              </div>

            </div>
          </div>
          <div class="text-link-bet-home-2">
            <p>Results available on <%= b.date + 7 %></p>
          </div>
        <% end %>

      <% end %>
    </div>

    <div class="lo--button-mauve-2">
      <%= link_to "Previous page", bets_home_path %>
    </div>

  <% end %>



</div>

app/views/bets/new.html.erb
<div class="lo--main-container">
<!-- <p>Find me in app/views/bets/new.html.erb</p> -->


<div>
    <h1 class="h1-new">It's time to challenge yourself!</h1>
</div>

  <%= simple_form_for(@bet) do |f| %>
    <div class="input-new-bet-2">
      <div class="input-new-bet">
        <%= f.input :amount, label: 'Amount', required: true %>
      </div>
      <div class="input-new-bet">
        <%= f.input :goal, label: 'Cigarette', required: true %>
      </div>
    </div>
    <div class="lo--button-white-new">
      <%= f.button :submit, "Submit"%>
    </div>
  <% end %>


<p class="p-new">
  You have <%= @user.wallet %> CAD on your balance
</p>
  <!-- redirect to index -->
  <div class="lo--button-mauve-2">
    <%= link_to "Previous page", bets_home_path %>
  </div>
</div>

app/views/bets/show.html.erb
<div class="lo--main-container">
<h1 style="font-weight: 700;
  font-size: 45px;
  border-bottom: 3px solid;
  color: white;
  text-align: center;" > <%= @betmessage %></h1>
<!-- <p>Find me in app/views/bets/show.html.erb</p> -->

<div class="text-bet-show">
  <div>
  Amount of your challenge : <%= @bet.amount %>
  </div>

  <div>
  Your Goal : <%= @bet.goal %>
  </div>

  <div>
  Your consumption for the Challenge period : <%= @consumption %>
  </div>

<br><br>

<!-- Display customized msg if challenge is won -->
<!-- Display customized msg if challenge is lost -->
  <div style="" id="betResult"><%= @bet.status %></div>
</div>


<br><br>
<div class="lo--button-mauve-bet-show">
<!-- redirect to index -->
<%= link_to "Back to all my challenges", bets_path %>
</div>

</div>