config/routes.rb
Rails.application.routes.draw do

  get '/landing', to: "pages#landing"

  get 'pages/menu'
  get 'bets/home'
  get 'savings/index'
  get '/graphs/home'
  post 'deposits', to: "users#deposit"
  post 'withdrawals', to: "users#withdraw"

  # get '/statistic', to: "pages#home"
  get 'horrible_facts/random', to: "horrible_facts#random", as: :random
  resources :consumptions, only: [:create, :update]
  resources :horrible_facts, only: [:index, :show,]
  resources :savings, only: [:index]
  resources :bets, only: [:index, :show, :new, :create]
  devise_for :users



  root to: 'consumptions#home'

  get "/style", to: "pages#style"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_footer.html.erb
<div class="lo--footer">

  <div class="lo--footer-content">
    <div class="lo--footer-icon">
      <i class="fas fa-binoculars"></i>
    </div>

    <h4 class="lo--footer-text">
      <%= link_to "Summary", root_path %>
    </h4>
  </div>


  <div class="lo--footer-content">
    <div class="lo--footer-icon">
      <i class="fas fa-chart-pie"></i>
    </div>

    <h4 class="lo--footer-text">
      <%= link_to "Evolution", graphs_home_path %>
    </h4>
  </div>

  <div class="lo--footer-content">
    <div class="lo--footer-icon">
      <i class="fas fa-exclamation-triangle"></i>
    </div>

    <h4 class="lo--footer-text">
      <%= link_to "Horrible Facts", horrible_facts_path %>
    </h4>
  </div>


  <div class="lo--footer-content">
    <div class="lo--footer-icon">
      <i class="fas fa-user-alt"></i>
    </div>

    <h4 class="lo--footer-text">
      <%= link_to "Account", pages_menu_path %>
    </h4>

  </div>

</div>

app/views/shared/_navbar.html.erb
<div class="lo--navbar">

  <div class="content">
    <h1 class="title"><%= @navbar_title ? @navbar_title : "last one"  %></h1>
    <img class="navbar-avatar" src="https://molnarfuneralhome.com/tribute-images/7765/Ultra/Robert-Bob-Mexico.jpg" alt="">
  </div>

</div>