config/routes.rb
Rails.application.routes.draw do

  get '/landing', to: "pages#landing"

  get 'pages/menu'
  get 'bets/home'
  get 'savings/index'
  get '/graphs/home'
  post 'deposits', to: "users#deposit"
  post 'withdrawals', to: "users#withdraw"

  # get '/statistic', to: "pages#home"
  get 'horrible_facts/random', to: "horrible_facts#random", as: :random
  resources :consumptions, only: [:create, :update]
  resources :horrible_facts, only: [:index, :show,]
  resources :savings, only: [:index]
  resources :bets, only: [:index, :show, :new, :create]
  devise_for :users



  root to: 'consumptions#home'

  get "/style", to: "pages#style"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/pages/home.html.erb
<h1>Pages#home</h1>

app/views/pages/landing.html.erb
<div class="lo--landing-page">
  <%= image_tag "ast_one.jpg", alt: "logo last one", class: "lo--landing-logo" %>

  <div class="lo--landing-container">

   <div class="lo--landing-content">
      <h1>Find the real Last One</h1>
      <!--<p class="lo--landing-text">Find the real Last One</p>-->
      <%= link_to "Quit already", root_path, class: "lo--button-white-l" %>
    </div>

  </div>



</div>

app/views/pages/menu.html.erb
<div class="lo--main-container">

<!-- style="padding-top: 80px"
 -->
<div class="lo--account">
  <div class="lo--account-content">
    <div class="lo--account-icon">
      <i class="fas fa-trophy"></i>
    </div>
    <h4 class="lo--account-text">
      <%= link_to "Challenge Yourself", bets_home_path, class: "lo--account-text" %>
    </h4>

  </div>

  <div class="lo--account-content">
    <div class="lo--account-icon">
      <i class="fas fa-bell"></i>
    </div>
    <h4 class="lo--account-text">
      Notifications Settings
    </h4>

  </div>

  <div class="lo--account-content">
    <div class="lo--account-icon">
      <i class="far fa-edit"></i>
    </div>
    <h4 class="lo--account-text">
      Account settings
    </h4>

  </div>

  <div class="lo--account-content">
    <div class="lo--account-icon">
      <i class="fas fa-sign-out-alt"></i>
    </div>
    <h4 class="lo--account-text">
        <%= link_to "Log Out", destroy_user_session_path, method: :delete %>
    </h4>

  </div>
</div>



</div>

app/views/pages/style.html.erb
<div class="style-main">
   <img class="style-main" style="" src="https://res.cloudinary.com/dim7avfq3/image/upload/v1575586085/ast_one_vckr2i.jpg" alt="">
</div>

<div class="background">
 <p class="background">hello</p>
</div>

app/views/pages/style2.html.erb
<h1>page to handle all components</h1>


<a href="#" class="lo--button-white">submit</a>

<a href="#" class="lo--button-mauve">submit</a>

<div class="lo--button-circle">
  <a href="#">+</a>
</div>

<a href="#" class="lo--button-transp">submit</a>


<br>


<div class="lo--navbar">

  <div class="content">
    <h1 class="title">test text</h1>
    <img class="navbar-avatar" src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" alt="">
  </div>

</div>

<br>

<br>


<div class="lo--footer">

  <div class="lo--footer-content">
    <div class="lo--footer-icon">
      <i class="fas fa-binoculars"></i>
    </div>

    <h4 class="lo--footer-text">
      Summary
    </h4>
  </div>


  <div class="lo--footer-content">
    <div class="lo--footer-icon">
      <i class="fas fa-chart-pie"></i>
    </div>

    <h4 class="lo--footer-text">
      Evolution
    </h4>
  </div>

  <div class="lo--footer-content">
    <div class="lo--footer-icon">
      <i class="fas fa-exclamation-triangle"></i>
    </div>

    <h4 class="lo--footer-text">
      Horrible Facts
    </h4>
  </div>


  <div class="lo--footer-content">
    <div class="lo--footer-icon">
      <i class="fas fa-user-alt"></i>
    </div>

    <h4 class="lo--footer-text">
      Accounts
    </h4>
  </div>

</div>


<div class="lo--friends-content">
  <img class="lo--friends-avatar" src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" alt="">

  <h3 class="lo--friends-text">
    Benjamin
  </h3>

  <div class="lo--friends-icon">
    <i class="far fa-check-square"></i>
  </div>

</div>
<div class="lo--circle-main">
  <div class="lo--circle">
    <h2 class="lo--circle-text">
      10
    </h2>
  </div>
</div>

<br>
<br>
<br>
<br>


<div class="lo--account">
  <div class="lo--account-content">
    <div class="lo--account-icon">
      <i class="far fa-edit"></i>
    </div>
    <h4 class="lo--account-text">
      Edit my account
    </h4>

  </div>

  <div class="lo--account-content">
    <div class="lo--account-icon">
      <i class="fas fa-trophy"></i>
    </div>
    <h4 class="lo--account-text">
      Challenge yourself
    </h4>

  </div>

  <div class="lo--account-content">
    <div class="lo--account-icon">
      <i class="far fa-bell"></i>
    </div>
    <h4 class="lo--account-text">
      Notifications frequency
    </h4>

  </div>

  <div class="lo--account-content">
    <div class="lo--account-icon">
      <i class="fas fa-sign-out-alt"></i>
    </div>
    <h4 class="lo--account-text">
      Log out
    </h4>

  </div>
</div>