config/routes.rb
Rails.application.routes.draw do

  get '/landing', to: "pages#landing"

  get 'pages/menu'
  get 'bets/home'
  get 'savings/index'
  get '/graphs/home'
  post 'deposits', to: "users#deposit"
  post 'withdrawals', to: "users#withdraw"

  # get '/statistic', to: "pages#home"
  get 'horrible_facts/random', to: "horrible_facts#random", as: :random
  resources :consumptions, only: [:create, :update]
  resources :horrible_facts, only: [:index, :show,]
  resources :savings, only: [:index]
  resources :bets, only: [:index, :show, :new, :create]
  devise_for :users



  root to: 'consumptions#home'

  get "/style", to: "pages#style"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/horrible_fact.rb
class HorribleFact < ApplicationRecord




  def notify
    # "User.first" for testing purposes, to be replaced by "current_user"
    mail = HorribleFactMailer.with(user: User.first).scareuser
    mail.deliver_now
  end



end

app/controllers/horrible_facts_controller.rb
class HorribleFactsController < ApplicationController

  def index
    @navbar_title = "Horrible Facts"
    if !user_signed_in?
      redirect_to new_user_session_path
    else
    @horrible_facts = HorribleFact.all
    end
  end

  def show
    @navbar_title = "Horrible Facts"
    #display the HF once the user has clicks on one horrible fact OR display one HF randomly
    @horrible_fact = HorribleFact.where(id: params[:id])


  end

  def random
    @navbar_title = "Horrible Facts"
    if !user_signed_in?
      redirect_to new_user_session_path
    else
    @horrible_facts = HorribleFact.all.shuffle
    end
  end

end

#Pages for horrible facts:

#Link in the email
#We should use the same page (horribleFacts/show/id). The links brings to this page with a horrible fact displayed randomly.
#Then the user can sweep right or left to see other horrible facts

#page horriblefact on the application
#We should use the same page (horribleFacts/show/id). The user can sweep right or left to see other horrible facts




#How to code the page regarding the possibility to sweep left/right ?

app/views/horrible_facts/index.html.erb
<div class="lo--main-container">




  <div class="hf-index" id="random_fact">
      <h2><%= link_to "Display horribles facts RANDOMLY", random_path, class:"page-mylink" %></h2>
  </div>

<% @horrible_facts.each do |hf| %>
<div class="hf-index">
    <h2><%= link_to hf.fact, horrible_fact_path(hf.id), class:"page-mylink" %></h2>
</div>
<% end %>



</div>

app/views/horrible_facts/random.html.erb
<% @horrible_fact = @horrible_facts.first %>
<% content_for :meta_title, "This is what happens when you smoke" %>
<% content_for :meta_description, @horrible_fact.fact %>
<% content_for :meta_image, @horrible_fact.photo %>

<div class="lo--main-container">

  <!-- Load Facebook SDK for JavaScript -->
  <div id="fb-root">
  </div>

  <script>(function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v3.0";
    fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));</script>

  <!-- Your share button code -->
  <div class="fb-share-button"
    data-href="https://mylast1.herokuapp.com/horrible_facts/<%= @horrible_fact.id %>"
    data-layout="button_count"
    style="margin-top: auto; margin-bottom: 100px; margin-left: auto;">
  </div>

  <div class="horrible-fact-slider">

    <% @horrible_facts.each do |hf| %>
    
      <div id="<%= hf.id %>" class="main-div-hf random-card">

        <div class="card-fact">
          <p class="<%= hf.id %>-fact"><%=hf.fact%></p>
        </div>

        <div class="card-photo">
          <img class="<%= hf.id %>-photo" src=<%= hf.photo %> >
        </div>

      </div>

    <% end %>
  
  </div>
</div>


<%= javascript_pack_tag 'slider' %>

app/views/horrible_facts/show.html.erb
<% @horrible_f = @horrible_fact.first %>
<% content_for :meta_title, "This is what happens when you smoke" %>
<% content_for :meta_description, @horrible_f.fact %>
<% content_for :meta_image, @horrible_f.photo %>

<div class="lo--main-container" >

  <!-- Load Facebook SDK for JavaScript -->
  <div id="fb-root">
  </div>

  <script>(function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v3.0";
    fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));</script>

  <!-- Your share button code -->
  <div class="fb-share-button"
    data-href="https://mylast1.herokuapp.com/horrible_facts/<%= @horrible_f.id %>"
    data-layout="button_count"
    style="margin-top: auto; margin-bottom: 100px; margin-left: auto;">
  </div>

    <% @horrible_fact.each do |hf| %>

      <div id="<%= hf.id %>" class="main-div-hf">

        <div class="card-fact">
          <p class="<%= hf.id %>-fact"><%= hf.fact%></p>
        </div>

        <div class="card-photo">
          <img class="<%= hf.id %>-photo" src=<%= hf.photo %> >
        </div>

      </div>

    <% end %>
    
  </div>
</div>